In [1]:
import pandas as pd
import numpy as np

In [2]:
# Create a sample dataset with data-quality problems

data = {
    "CustomerID": [101, 102, 103, 104, 105, 106, 102],
    "Name": ["Meghana", "Ravi", "Priya", "Arun", "Kiran", "Sita", "Ravi"],
    "Age": [25, np.nan, "twenty-five", -5, 40, 30, np.nan],
    "Gender": ["Female", " male ", "F", "Other", "MALE", None, " male "],
    "City": ["Chennai", " chennai ", "Bengaluru", "HYDERABAD",
             "Hyderabad", None, " chennai "],
    "Salary": ["50000", "60000", "70000", "-5000", "85,000", None, "60000"]
}

df = pd.DataFrame(data)

df.to_csv("raw_customers.csv", index=False)

df = pd.read_csv("raw_customers.csv")

print("Dataset loaded successfully!")
df

Dataset loaded successfully!

   CustomerID     Name          Age  Gender       City  Salary
0         101  Meghana           25  Female    Chennai   50000
1         102     Ravi          NaN   male    chennai    60000
2         103    Priya  twenty-five       F  Bengaluru   70000
3         104     Arun           -5   Other  HYDERABAD   -5000
4         105    Kiran           40    MALE  Hyderabad  85,000
5         106     Sita           30     NaN        NaN     NaN
6         102     Ravi          NaN   male    chennai    60000

In [3]:

display(df.head())

print("Shape:", df.shape)

print("\nDataset information:")
df.info()

display(df.describe(include="all"))

print("\nMissing values:")
print(df.isnull().sum())

   CustomerID     Name          Age  Gender       City  Salary
0         101  Meghana           25  Female    Chennai   50000
1         102     Ravi          NaN   male    chennai    60000
2         103    Priya  twenty-five       F  Bengaluru   70000
3         104     Arun           -5   Other  HYDERABAD   -5000
4         105    Kiran           40    MALE  Hyderabad  85,000

Shape: (7, 6)

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerID  7 non-null      int64
 1   Name        7 non-null      str
 2   Age         5 non-null      str
 3   Gender      6 non-null      str
 4   City        6 non-null      str
 5   Salary      6 non-null      str
dtypes: int64(1), str(5)
memory usage: 468.0 bytes

        CustomerID  Name  Age  Gender       City Salary
count     7.000000     7    5       6          6      6
unique         NaN     6    5       5          5      5
top            NaN  Ravi   25   male    chennai   60000
freq           NaN     2    1       2          2      2
mean    103.285714   NaN  NaN     NaN        NaN    NaN
std       1.799471   NaN  NaN     NaN        NaN    NaN
min     101.000000   NaN  NaN     NaN        NaN    NaN
25%     102.000000   NaN  NaN     NaN        NaN    NaN
50%     103.000000   NaN  NaN     NaN        NaN    NaN
75%     104.500000   NaN  NaN     NaN        NaN    NaN
max     106.000000   NaN  NaN     NaN        NaN    NaN

Missing values:
CustomerID    0
Name          0
Age           2
Gender        1
City          1
Salary        1
dtype: int64

In [12]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")


df["Salary"] = pd.to_numeric(
    df["Salary"].astype("string").str.replace(",", "", regex=False),
    errors="coerce"
)
df.loc[df["Age"] < 0, "Age"] = np.nan
df.loc[df["Salary"] < 0, "Salary"] = np.nan
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerID  7 non-null      int64
 1   Name        7 non-null      str
 2   Age         3 non-null      float64
 3   Gender      6 non-null      str
 4   City        6 non-null      str
 5   Salary      5 non-null      Int64
dtypes: Int64(1), float64(1), int64(1), str(3)
memory usage: 475.0 bytes

In [14]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Salary"] = df["Salary"].fillna(df["Salary"].median())

df["Gender"] = df["Gender"].fillna("Unknown")
df["City"] = df["City"].fillna("Unknown")

print(df.isnull().sum())
display(df)

CustomerID    0
Name          0
Age           0
Gender        0
City          0
Salary        0
dtype: int64

   CustomerID     Name   Age   Gender       City  Salary
0         101  Meghana  25.0   Female    Chennai   50000
1         102     Ravi  30.0    male    chennai    60000
2         103    Priya  30.0        F  Bengaluru   70000
3         104     Arun  30.0    Other  HYDERABAD   60000
4         105    Kiran  40.0     MALE  Hyderabad   85000
5         106     Sita  30.0  Unknown    Unknown   60000
6         102     Ravi  30.0    male    chennai    60000

In [18]:
print("Duplicate rows:", df.duplicated().sum())
display(df[df.duplicated(keep=False)])
df = df.drop_duplicates()
df = df.reset_index(drop=True)
print("Shape after removing duplicates:", df.shape)

Duplicate rows: 1

   CustomerID  Name   Age  Gender       City  Salary
1         102  Ravi  30.0   male    chennai    60000
6         102  Ravi  30.0   male    chennai    60000

Shape after removing duplicates: (6, 6)

In [22]:
df["Name"] = df["Name"].str.strip()
df["City"] = df["City"].str.strip().str.title()
df["Gender"] = df["Gender"].str.strip().str.title()
df["Age"] = df["Age"].round().astype("int64")
df["Salary"] = df["Salary"].astype("float64")
df["CustomerID"] = df["CustomerID"].astype("int64")
print(df.dtypes)
display(df)

CustomerID      int64
Name              str
Age             int64
Gender            str
City              str
Salary        float64
dtype: object

   CustomerID     Name  Age   Gender       City   Salary
0         101  Meghana   25   Female    Chennai  50000.0
1         102     Ravi   30     Male    Chennai  60000.0
2         103    Priya   30        F  Bengaluru  70000.0
3         104     Arun   30    Other  Hyderabad  60000.0
4         105    Kiran   40     Male  Hyderabad  85000.0
5         106     Sita   30  Unknown    Unknown  60000.0

In [24]:
gender_mapping = {
    "F": "Female",
    "Female": "Female",
    "M": "Male",
    "Male": "Male",
    "Other": "Other",
    "Unknown": "Unknown"
}
df["Gender"] = df["Gender"].map(gender_mapping).fillna("Unknown")
invalid_ages = df[(df["Age"] < 0) | (df["Age"] > 120)]
print("Invalid ages:")
display(invalid_ages)

invalid_salaries = df[df["Salary"] < 0]
print("Invalid salaries:")
display(invalid_salaries)

print("Gender categories:", df["Gender"].unique())
print("Cities:", df["City"].unique())

Invalid ages:

Empty DataFrame
Columns: [CustomerID, Name, Age, Gender, City, Salary]
Index: []

Invalid salaries:

Empty DataFrame
Columns: [CustomerID, Name, Age, Gender, City, Salary]
Index: []

Gender categories: <StringArray>
['Female', 'Male', 'Other', 'Unknown']
Length: 4, dtype: str
Cities: <StringArray>
['Chennai', 'Bengaluru', 'Hyderabad', 'Unknown']
Length: 4, dtype: str

In [25]:
# Transformation: create a salary band
df["SalaryBand"] = np.where(
    df["Salary"] >= 70000,
    "High",
    "Standard"
)

# Encoding: create binary columns for each gender category
df = pd.get_dummies(
    df,
    columns=["Gender"],
    prefix="Gender",
    dtype=int
)

# Normalization: scale Age and Salary to the range 0 to 1
df["Age_Normalized"] = (
    (df["Age"] - df["Age"].min()) /
    (df["Age"].max() - df["Age"].min())
    if df["Age"].max() != df["Age"].min()
    else 0.0
)

df["Salary_Normalized"] = (
    (df["Salary"] - df["Salary"].min()) /
    (df["Salary"].max() - df["Salary"].min())
    if df["Salary"].max() != df["Salary"].min()
    else 0.0
)

display(df)

,CustomerID,Name,Age,City,Salary,SalaryBand,Gender_Female,Gender_Male,Gender_Other,Gender_Unknown,Age_Normalized,Salary_Normalized
0,101,Meghana,25,Chennai,50000.0,Standard,1,0,0,0,0.000000,0.000000
1,102,Ravi,30,Chennai,60000.0,Standard,0,1,0,0,0.333333,0.285714
2,103,Priya,30,Bengaluru,70000.0,High,1,0,0,0,0.333333,0.571429
3,104,Arun,30,Hyderabad,60000.0,Standard,0,0,1,0,0.333333,0.285714
4,105,Kiran,40,Hyderabad,85000.0,High,0,1,0,0,1.000000,1.000000
5,106,Sita,30,Unknown,60000.0,Standard,0,0,0,1,0.333333,0.285714

In [26]:
# Filter customers whose salary is at least 60000
high_salary_customers = df[df["Salary"] >= 60000]
display(high_salary_customers)

# Sort customers by salary, highest first
sorted_customers = df.sort_values(
    by="Salary",
    ascending=False
)
display(sorted_customers)

# Aggregate data by city
city_summary = df.groupby("City").agg(
    Customer_Count=("CustomerID", "count"),
    Average_Age=("Age", "mean"),
    Average_Salary=("Salary", "mean"),
    Total_Salary=("Salary", "sum")
).reset_index()

display(city_summary)

,CustomerID,Name,Age,City,Salary,SalaryBand,Gender_Female,Gender_Male,Gender_Other,Gender_Unknown,Age_Normalized,Salary_Normalized
1,102,Ravi,30,Chennai,60000.0,Standard,0,1,0,0,0.333333,0.285714
2,103,Priya,30,Bengaluru,70000.0,High,1,0,0,0,0.333333,0.571429
3,104,Arun,30,Hyderabad,60000.0,Standard,0,0,1,0,0.333333,0.285714
4,105,Kiran,40,Hyderabad,85000.0,High,0,1,0,0,1.000000,1.000000
5,106,Sita,30,Unknown,60000.0,Standard,0,0,0,1,0.333333,0.285714

,CustomerID,Name,Age,City,Salary,SalaryBand,Gender_Female,Gender_Male,Gender_Other,Gender_Unknown,Age_Normalized,Salary_Normalized
4,105,Kiran,40,Hyderabad,85000.0,High,0,1,0,0,1.000000,1.000000
2,103,Priya,30,Bengaluru,70000.0,High,1,0,0,0,0.333333,0.571429
3,104,Arun,30,Hyderabad,60000.0,Standard,0,0,1,0,0.333333,0.285714
1,102,Ravi,30,Chennai,60000.0,Standard,0,1,0,0,0.333333,0.285714
5,106,Sita,30,Unknown,60000.0,Standard,0,0,0,1,0.333333,0.285714
0,101,Meghana,25,Chennai,50000.0,Standard,1,0,0,0,0.000000,0.000000

        City  Customer_Count  Average_Age  Average_Salary  Total_Salary
0  Bengaluru               1         30.0         70000.0       70000.0
1    Chennai               2         27.5         55000.0      110000.0
2  Hyderabad               2         35.0         72500.0      145000.0
3    Unknown               1         30.0         60000.0       60000.0

In [27]:
# Export the cleaned dataset
df.to_csv("cleaned_customers.csv", index=False)

print("Cleaned dataset exported successfully!")

Cleaned dataset exported successfully!