In [1]:
import pandas as pd

In [3]:
# Load the e-commerce dataset
df = pd.read_csv("ecommerce.csv")

# Display the dataset
display(df)

    OrderID             Product  UnitPrice  Quantity       City Customer
0      1001              Laptop    55000.0       1.0    Chennai     Ravi
1      1002        Mobile Phone    25000.0       2.0  Bengaluru    Priya
2      1003          Headphones     2500.0       3.0  Hyderabad     Arun
3      1004            Keyboard     1500.0       2.0    Chennai     Sita
4      1005             Monitor    12000.0       1.0     Mumbai    Kiran
5      1006              Laptop    55000.0       1.0  Hyderabad     Anil
6      1007         Smart Watch     8000.0       2.0    Chennai    Meena
7      1008              Tablet    18000.0       1.0  Bengaluru    Rahul
8      1009               Mouse      800.0       4.0     Mumbai    Divya
9      1010        Gaming Chair    15000.0       1.0  Hyderabad    Vijay
10     1011             Printer     9000.0       2.0    Chennai      Anu
11     1012        Mobile Phone    25000.0       1.0  Bengaluru     Ravi
12     1013              Webcam     4500.0       2.0     Mumbai   Suresh
13     1014              Laptop    55000.0       1.0    Chennai    Priya
14     1015             Monitor    12000.0       2.0  Hyderabad    Kiran
15     1003          Headphones     2500.0       3.0  Hyderabad     Arun
16     1016  External Hard Disk     6500.0       2.0  Bengaluru    Meena
17     1017         Smart Watch        NaN       1.0    Chennai    Rahul
18     1018              Tablet    18000.0       2.0        NaN    Divya
19     1019            Keyboard     1500.0       NaN     Mumbai    Vijay
20     1020             Printer     9000.0       1.0    Chennai      NaN

In [4]:
# Display first 5 records
print("First 5 records:")
display(df.head())

# Display number of rows and columns
print("Dataset shape:", df.shape)

# Display column names and data types
print("\nDataset information:")
df.info()

# Display statistical summary
print("\nStatistical summary:")
display(df.describe())

First 5 records:

   OrderID       Product  UnitPrice  Quantity       City Customer
0     1001        Laptop    55000.0       1.0    Chennai     Ravi
1     1002  Mobile Phone    25000.0       2.0  Bengaluru    Priya
2     1003    Headphones     2500.0       3.0  Hyderabad     Arun
3     1004      Keyboard     1500.0       2.0    Chennai     Sita
4     1005       Monitor    12000.0       1.0     Mumbai    Kiran

Dataset shape: (21, 6)

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    21 non-null     int64
 1   Product    21 non-null     str
 2   UnitPrice  20 non-null     float64
 3   Quantity   20 non-null     float64
 4   City       20 non-null     str
 5   Customer   20 non-null     str
dtypes: float64(2), int64(1), str(3)
memory usage: 1.1 KB

Statistical summary:

           OrderID     UnitPrice   Quantity
count    21.000000     20.000000  20.000000
mean   1010.142857  16790.000000   1.750000
std       5.994045  17997.160595   0.850696
min    1001.000000    800.000000   1.000000
25%    1005.000000   4000.000000   1.000000
50%    1010.000000  10500.000000   2.000000
75%    1015.000000  19750.000000   2.000000
max    1020.000000  55000.000000   4.000000

In [5]:
# Check whether each value is missing
print("Missing value matrix:")
display(df.isnull())

# Count missing values in every column
missing_values = df.isnull().sum()

print("\nMissing values in each column:")
print(missing_values)

Missing value matrix:

    OrderID  Product  UnitPrice  Quantity   City  Customer
0     False    False      False     False  False     False
1     False    False      False     False  False     False
2     False    False      False     False  False     False
3     False    False      False     False  False     False
4     False    False      False     False  False     False
5     False    False      False     False  False     False
6     False    False      False     False  False     False
7     False    False      False     False  False     False
8     False    False      False     False  False     False
9     False    False      False     False  False     False
10    False    False      False     False  False     False
11    False    False      False     False  False     False
12    False    False      False     False  False     False
13    False    False      False     False  False     False
14    False    False      False     False  False     False
15    False    False      False     False  False     False
16    False    False      False     False  False     False
17    False    False       True     False  False     False
18    False    False      False     False   True     False
19    False    False      False      True  False     False
20    False    False      False     False  False      True

Missing values in each column:
OrderID      0
Product      0
UnitPrice    1
Quantity     1
City         1
Customer     1
dtype: int64

In [6]:
# Display only columns that contain missing values
missing_columns = missing_values[missing_values > 0]

print("Columns containing missing values:")
print(missing_columns)

Columns containing missing values:
UnitPrice    1
Quantity     1
City         1
Customer     1
dtype: int64

In [7]:
# Fill missing UnitPrice using the median
df["UnitPrice"] = df["UnitPrice"].fillna(df["UnitPrice"].median())

# Fill missing Quantity using the median
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].median())

In [8]:
# Fill missing city with Unknown
df["City"] = df["City"].fillna("Unknown")

# Fill missing customer with Unknown
df["Customer"] = df["Customer"].fillna("Unknown")

In [9]:
print(df.isnull().sum())

OrderID      0
Product      0
UnitPrice    0
Quantity     0
City         0
Customer     0
dtype: int64

In [10]:
# Count occurrences of every Order ID
order_counts = df["OrderID"].value_counts()

print("Order ID counts:")
print(order_counts)

Order ID counts:
OrderID
1003    2
1001    1
1002    1
1004    1
1005    1
1006    1
1007    1
1008    1
1009    1
1010    1
1011    1
1012    1
1013    1
1014    1
1015    1
1016    1
1017    1
1018    1
1019    1
1020    1
Name: count, dtype: int64

In [11]:
# Identify repeated Order IDs
duplicate_order_ids = order_counts[order_counts > 1]

print("Repeated Order IDs:")
print(duplicate_order_ids)

Repeated Order IDs:
OrderID
1003    2
Name: count, dtype: int64

In [12]:
# Identify repeated Order IDs
duplicate_order_ids = order_counts[order_counts > 1]

print("Repeated Order IDs:")
print(duplicate_order_ids)

Repeated Order IDs:
OrderID
1003    2
Name: count, dtype: int64

In [13]:
# Display all records having duplicate Order IDs
duplicate_records = df[df["OrderID"].isin(duplicate_order_ids.index)]

print("Duplicate records:")
display(duplicate_records)

Duplicate records:

    OrderID     Product  UnitPrice  Quantity       City Customer
2      1003  Headphones     2500.0       3.0  Hyderabad     Arun
15     1003  Headphones     2500.0       3.0  Hyderabad     Arun

In [14]:
# Check for completely identical rows
print("Number of exact duplicate rows:")
print(df.duplicated().sum())

Number of exact duplicate rows:
1

In [15]:
# Remove completely duplicated rows
df = df.drop_duplicates()

# Reset index after removing duplicates
df = df.reset_index(drop=True)

print("Dataset shape after removing duplicates:", df.shape)

Dataset shape after removing duplicates: (20, 6)

In [16]:
# Verify that the duplicate row has been removed
print("Duplicate rows after cleaning:")
print(df.duplicated().sum())

Duplicate rows after cleaning:
0

In [17]:
# Find the highest UnitPrice
highest_price = df["UnitPrice"].max()

print("Highest UnitPrice:", highest_price)

Highest UnitPrice: 55000.0

In [18]:
# Find the product with the highest UnitPrice
highest_priced_product = df.loc[
    df["UnitPrice"].idxmax()
]

print("Highest-priced product:")
display(highest_priced_product)

Highest-priced product:

OrderID         1001
Product       Laptop
UnitPrice    55000.0
Quantity         1.0
City         Chennai
Customer        Ravi
Name: 0, dtype: object

In [19]:
print(
    "Highest-priced product:",
    highest_priced_product["Product"]
)

print(
    "Price:",
    highest_priced_product["UnitPrice"]
)

Highest-priced product: Laptop
Price: 55000.0

In [20]:
# Calculate revenue for every order
df["Revenue"] = df["UnitPrice"] * df["Quantity"]

display(df)

,OrderID,Product,UnitPrice,Quantity,City,Customer,Revenue
0,1001,Laptop,55000.0,1.0,Chennai,Ravi,55000.0
1,1002,Mobile Phone,25000.0,2.0,Bengaluru,Priya,50000.0
2,1003,Headphones,2500.0,3.0,Hyderabad,Arun,7500.0
3,1004,Keyboard,1500.0,2.0,Chennai,Sita,3000.0
4,1005,Monitor,12000.0,1.0,Mumbai,Kiran,12000.0
5,1006,Laptop,55000.0,1.0,Hyderabad,Anil,55000.0
6,1007,Smart Watch,8000.0,2.0,Chennai,Meena,16000.0
7,1008,Tablet,18000.0,1.0,Bengaluru,Rahul,18000.0
8,1009,Mouse,800.0,4.0,Mumbai,Divya,3200.0
9,1010,Gaming Chair,15000.0,1.0,Hyderabad,Vijay,15000.0
10,1011,Printer,9000.0,2.0,Chennai,Anu,18000.0
11,1012,Mobile Phone,25000.0,1.0,Bengaluru,Ravi,25000.0
12,1013,Webcam,4500.0,2.0,Mumbai,Suresh,9000.0
13,1014,Laptop,55000.0,1.0,Chennai,Priya,55000.0
14,1015,Monitor,12000.0,2.0,Hyderabad,Kiran,24000.0
15,1016,External Hard Disk,6500.0,2.0,Bengaluru,Meena,13000.0
16,1017,Smart Watch,10500.0,1.0,Chennai,Rahul,10500.0
17,1018,Tablet,18000.0,2.0,Unknown,Divya,36000.0
18,1019,Keyboard,1500.0,2.0,Mumbai,Vijay,3000.0
19,1020,Printer,9000.0,1.0,Chennai,Unknown,9000.0

In [21]:
# Calculate total revenue for each city
city_revenue = df.groupby("City")["Revenue"].sum()

print("City-wise revenue:")
print(city_revenue)

City-wise revenue:
City
Bengaluru    106000.0
Chennai      166500.0
Hyderabad    101500.0
Mumbai        27200.0
Unknown       36000.0
Name: Revenue, dtype: float64

In [22]:
# Create a city-wise revenue summary
city_revenue = (
    df.groupby("City", as_index=False)["Revenue"]
      .sum()
      .sort_values("Revenue", ascending=False)
)

display(city_revenue)

        City   Revenue
1    Chennai  166500.0
0  Bengaluru  106000.0
2  Hyderabad  101500.0
4    Unknown   36000.0
3     Mumbai   27200.0

In [23]:
# Fill missing numerical values
df["UnitPrice"] = df["UnitPrice"].fillna(df["UnitPrice"].median())
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].median())

# Fill missing city
df["City"] = df["City"].fillna("Unknown")

# Fill missing customer
df["Customer"] = df["Customer"].fillna("Unknown")

# Calculate revenue after cleaning
df["Revenue"] = df["UnitPrice"] * df["Quantity"]

display(df)

,OrderID,Product,UnitPrice,Quantity,City,Customer,Revenue
0,1001,Laptop,55000.0,1.0,Chennai,Ravi,55000.0
1,1002,Mobile Phone,25000.0,2.0,Bengaluru,Priya,50000.0
2,1003,Headphones,2500.0,3.0,Hyderabad,Arun,7500.0
3,1004,Keyboard,1500.0,2.0,Chennai,Sita,3000.0
4,1005,Monitor,12000.0,1.0,Mumbai,Kiran,12000.0
5,1006,Laptop,55000.0,1.0,Hyderabad,Anil,55000.0
6,1007,Smart Watch,8000.0,2.0,Chennai,Meena,16000.0
7,1008,Tablet,18000.0,1.0,Bengaluru,Rahul,18000.0
8,1009,Mouse,800.0,4.0,Mumbai,Divya,3200.0
9,1010,Gaming Chair,15000.0,1.0,Hyderabad,Vijay,15000.0
10,1011,Printer,9000.0,2.0,Chennai,Anu,18000.0
11,1012,Mobile Phone,25000.0,1.0,Bengaluru,Ravi,25000.0
12,1013,Webcam,4500.0,2.0,Mumbai,Suresh,9000.0
13,1014,Laptop,55000.0,1.0,Chennai,Priya,55000.0
14,1015,Monitor,12000.0,2.0,Hyderabad,Kiran,24000.0
15,1016,External Hard Disk,6500.0,2.0,Bengaluru,Meena,13000.0
16,1017,Smart Watch,10500.0,1.0,Chennai,Rahul,10500.0
17,1018,Tablet,18000.0,2.0,Unknown,Divya,36000.0
18,1019,Keyboard,1500.0,2.0,Mumbai,Vijay,3000.0
19,1020,Printer,9000.0,1.0,Chennai,Unknown,9000.0

In [24]:
# Calculate final city-wise revenue
city_revenue = (
    df.groupby("City", as_index=False)["Revenue"]
      .sum()
      .sort_values("Revenue", ascending=False)
)

display(city_revenue)

        City   Revenue
1    Chennai  166500.0
0  Bengaluru  106000.0
2  Hyderabad  101500.0
4    Unknown   36000.0
3     Mumbai   27200.0